# Generated by Django 5.2 on 2025-05-24 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_customuser_secondary_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='user',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'fournisseur'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fournisseur_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
