# Generated by Django 5.2 on 2025-05-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_twofactorcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='quantite',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(default='electronique', max_length=100),
        ),
    ]
