# Generated by Django 5.2 on 2025-05-05 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_quantite_alter_article_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='article',
            name='fournisseur',
        ),
        migrations.AddField(
            model_name='article',
            name='quantite',
            field=models.IntegerField(default=0, help_text='Quantité réelle en stock'),
        ),
        migrations.AddField(
            model_name='article',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stock',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', related_query_name='stock_entries', to='inventory.article'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='entree',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sortie',
            field=models.IntegerField(default=0),
        ),
    ]
