# Generated by Django 5.2 on 2025-05-05 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_article_categorie_remove_article_fournisseur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quantite',
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='stock',
            field=models.IntegerField(default=0, help_text='Stock calculé ou ajusté manuellement'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='inventory.categorie'),
        ),
    ]
