# Generated by Django 5.2 on 2025-05-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_demandearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='facteur_co2',
            field=models.FloatField(default=0.0, help_text='Renseigne le facteur d’émission de CO₂ pour ce produit (ADEME ou estimation, en kg par unité)', verbose_name="Facteur d'émission CO₂ (kg/unit)"),
        ),
    ]
