# Generated by Django 5.2 on 2025-05-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_categorie_remove_stock_quantite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(default='electronique', max_length=100),
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
