# Generated by Django 5.2 on 2025-05-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_article_categorie_delete_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('electronique', 'Électronique'), ('papeterie', 'Papeterie'), ('quincaillerie', 'Quincaillerie')], default='electronique', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
