# Generated by Django 5.2 on 2025-05-31 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_article_facteur_co2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_stock', to='inventory.article'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stock',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anciennes_entrees', to='inventory.article'),
        ),
    ]
