# Generated by Django 5.2 on 2025-05-31 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_mouvementstock_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.article'),
        ),
    ]
