# Generated by Django 5.2 on 2025-05-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_article_categorie_alter_article_quantite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(default='electronique', max_length=100),
        ),
    ]
