# Generated by Django 5.2 on 2025-05-05 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_article_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categorie',
        ),
        migrations.AlterField(
            model_name='article',
            name='quantite',
            field=models.IntegerField(default=0, help_text='Quantité réelle en stock'),
        ),
        migrations.AlterField(
            model_name='article',
            name='stock',
            field=models.IntegerField(default=0, help_text='Stock calculé ou ajusté manuellement'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='inventory.article'),
        ),
    ]
