# Generated by Django 5.2 on 2025-05-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_mouvementstock_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='facteur_co2',
            field=models.FloatField(default=0.0, verbose_name='Facteur CO₂ (kg/unité)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='quantite',
            field=models.IntegerField(default=0, help_text='Quantité réelle en stock (non utilisée pour entrées/sorties)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='stock',
            field=models.IntegerField(default=0, help_text='Stock calculé à partir des mouvements'),
        ),
    ]
