# Generated by Django 5.2 on 2025-05-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_article_facteur_co2_alter_article_quantite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='secondary_email',
            field=models.EmailField(blank=True, help_text='Adresse e-mail ajoutée via la procédure 2FA', max_length=254, null=True, unique=True, verbose_name='Email secondaire (2FA)'),
        ),
    ]
