# Generated by Django 5.2 on 2025-05-21 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='user',
            field=models.OneToOneField(default=1, limit_choices_to={'role': 'fournisseur'}, on_delete=django.db.models.deletion.CASCADE, related_name='fournisseur_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('gestionnaire', 'Gestionnaire de stock'), ('employe', 'Employé'), ('fournisseur', 'Fournisseur')], max_length=20),
        ),
    ]
