# Generated by Django 5.2 on 2025-06-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_article_alerte_envoyee_alter_article_stock_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='alerte_envoyee',
            field=models.BooleanField(default=False, help_text='True dès qu’une alerte a déjà été envoyée pour ce seuil'),
        ),
        migrations.AlterField(
            model_name='article',
            name='quantite',
            field=models.IntegerField(default=0, help_text='Quantité manuelle (visible à l’édition).'),
        ),
        migrations.AlterField(
            model_name='article',
            name='stock',
            field=models.IntegerField(default=0, help_text='Stock calculé à partir des mouvements (ou initialisé à quantite).'),
        ),
        migrations.AlterField(
            model_name='article',
            name='stock_min',
            field=models.PositiveIntegerField(default=1, help_text='Seuil minimal en stock pour déclencher une alerte'),
        ),
    ]
