# Generated by Django 5.2 on 2025-05-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_fournisseur_user_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactorcode',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
