# Generated by Django 5.2 on 2025-06-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_article_alerte_envoyee_alter_article_quantite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='stock_min',
            field=models.PositiveIntegerField(default=10, help_text='Seuil minimal en stock pour déclencher une alerte'),
        ),
    ]
