# Generated by Django 5.2 on 2025-05-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_twofactorcode_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
