# Generated by Django 5.2 on 2025-06-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_article_stock_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='stock_min',
            field=models.PositiveIntegerField(default=10, help_text='Seuil minimal en stock pour déclencher une alerte'),
        ),
    ]
