# Generated by Django 5.2 on 2025-06-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_article_stock_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='alerte_envoyee',
        ),
        migrations.AddField(
            model_name='article',
            name='alerte_stock_faible_envoyee',
            field=models.BooleanField(default=False, help_text="Passé à True dès qu'une alerte stock < 10 a été envoyée"),
        ),
        migrations.AlterField(
            model_name='article',
            name='quantite',
            field=models.IntegerField(default=0, help_text='Quantité initiale'),
        ),
        migrations.AlterField(
            model_name='article',
            name='stock',
            field=models.IntegerField(default=0, help_text='Stock courant'),
        ),
        migrations.AlterField(
            model_name='article',
            name='stock_min',
            field=models.PositiveIntegerField(default=1, help_text='Seuil minimal pour alerte'),
        ),
    ]
